// <auto-generated />
namespace MarsBurgerV1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addItemOrigID2OrderItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addItemOrigID2OrderItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201909042047074_addItemOrigID2OrderItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
